spring:
  application:
    name: matchService
  datasource:
    url: jdbc:postgresql://localhost:5433/daten
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8082

http-url:
  deck-service: http://localhost:8083

notification-like-topic: notification.event.like
notification-match-topic: notification.event.match