spring:
  application:
    name: userService
  datasource:
    url: jdbc:postgresql://localhost:5433/daten
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  kafka:
    consumer:
      group-id: desk-service-group
    bootstrap-servers: localhost:9092
server:
  port: 8080

profile-created-topic: deck.event